### ISSUE TITLE
Erro ao Chamar WebView de Login

### ISSUE THREAD

**Issue by gblnovaes** [stone-payments/onestap-sdk-android#5]
## Comportamento esperado
Abrir a webview para efetuar o login

## Comportamento atual
 No static field progress of type I in class Lcom/onestap/onestap/R$id; or its superclasses (declaration of 'com.onestap.onestap.R$id' 
 W/System.err: java.lang.NoSuchFieldError: No static field progress of type I in class Lcom/onestap/onestap/R$id; or its superclasses (declaration of 'com.onestap.onestap.R$id' appears in 

## Especificações
  - Versão da SDK:16
  - Versão do Android: 6.0

**Comment by mgribel** [comment]
@gblnovaes 
O bug relatado foi corrigido e está disponível na release #0.2.1

Obrigado pela colaboração.

Att,
